---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-redirect-handler
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 99
      services:
        - kind: TraefikService
          name: noop@internal
      middlewares:
        - name: redirect-to-https
---
