apiVersion: v2
name: traefik
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.18.0"
dependencies:
  - name: traefik
    version: 15.0.0
    repository: https://helm.traefik.io/traefik
