bases:
  - environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: traefik
    namespace: default
    chart: ./charts/traefik
    values:
      - ./charts/traefik/values.yaml.gotmpl