bases:
  - environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: default
    chart: ./charts/traefik
    values:
      - ./charts/traefik/values.yaml.gotmpl
  # - name: mongodb-app
  #   namespace: default
  #   chart: ./charts/mongodb
  #   values:
  #     - ./charts/mongodb/values.yaml.gotmpl