apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/vverenko/argo-sandbox
    targetRevision: master
    path: cluster
    plugin:
      env:
        - name: HELMFILE_GLOBAL_OPTIONS
          value: "-e dev"
      name: helmfile

  destination:
    server: https://18.134.147.100:6443
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
